version: '3.9'
services:
  openldap:
    image: osixia/openldap:latest
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ORGANISASTION=OPENLDAP
      - LDAP_DOMAIN=openldap.com
      - LDAP_ADMIN_PASSWORD=12345
    networks:
      - openldap-network
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_server_admin:
    image: osixia/phpldapadmin:latest
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
    networks:
      - openldap-network
networks:
  openldap-network:
    driver: bridge
volumes:
  ldap_data:
  ldap_config: